[project]
name = "coursekata-r-packages"
description = "R package dependencies for CourseKata Jupyter environments"

[dependencies]
IRkernel = "*"
rlang = "*"

[feature.essentials.dependencies]
coursekata = { force = true }
fivethirtyeight = "*"
fivethirtyeightdata = { github = "coursekata/fivethirtyeightdata" }
ggpubr = "*"
gridExtra = "*"
lme4 = "*"
Lock5withR = { github = "coursekata/Lock5withR" }
plotly = "*"
statmod = "*"
testwhat = { github = "coursekata/testwhat", tag = "v4.11.3.2" }

[feature.r.dependencies]
av = "*"
bayesplot = "*"
"broom.mixed" = "*"
car = "*"
dagitty = "*"
datapasta = "*"
DHARMa = "*"
easystats = "*"
emmeans = "*"
gganimate = "*"
ggdag = "*"
ggeffects = "*"
gifski = "*"
gt = "*"
gtsummary = "*"
here = "*"
janitor = "*"
lmerTest = "*"
loo = "*"
mapdata = "*"
mapproj = "*"
marginaleffects = "*"
mobilizr = { github = "mobilizingcs/mobilizr" }
neuralnet = "*"
OCSdata = "*"
posterior = "*"
profvis = "*"
psych = "*"
RcppTOML = "*"
reticulate = "*"
simstudy = "*"
sjPlot = "*"
Stat2Data = "*"
tidybayes = "*"
tidymodels = "*"
tidyverse = "*"
V8 = { force = true }

[feature.datascience.dependencies]
brms = "*"
cmdstanr = { repos = "https://mc-stan.org/r-packages/" }
ggstatsplot = "*"
nimble = "*"
rethinking = { github = "rmcelreath/rethinking", tag = "v2.2.1" }
rstanarm = "*"
simDAG = "*"

[environments.base-r-notebook]
features = []

[environments.essentials-notebook]
features = ["essentials"]

[environments.r-notebook]
features = ["essentials", "r"]

[environments.datascience-notebook]
features = ["essentials", "r", "datascience"]
