name: essentials-notebook
channels:
  - defaults
  - conda-forge
dependencies:
  - pip

  # essentials-notebook
  - r-coursekata
  - r-fivethirtyeight
  - r-ggpubr
  - r-gridextra
  - r-lme4
  - r-plotly
  - r-statmod
  - r-scales >=1.3.0
  ## for r-testwhat, not on conda
  - r-evaluate
  - r-magrittr
  - r-markdown
  - r-praise
  - r-r6
  - r-stringdist
  - r-xfun

  - pip:
      - pythonwhat @ git+https://github.com/coursekata/pythonwhat@master
