---
name: Build and Test all Images

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The platform to build on"
        type: string
        required: false
        default: "ubuntu-latest"
  push:
    branches: [test/*]
    paths:
      - .github/workflows/build-test-publish.yml
      - .github/workflows/test-all.yml
      - base-r-notebook/**
      - essentials-notebook/**
      - r-notebook/**
      - datascience-notebook/**

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: Set output variables based on the inputs
        id: set-env
        run: |
          echo "runs-on=${{ github.event.inputs.runs-on || 'ubuntu-latest' }}" >> $GITHUB_OUTPUT
    outputs:
      runs-on: ${{ steps.set-env.outputs.runs-on }}
      python-version: "3.11"
      r-version: "4.3"
      tags: |
        type=raw,value=python-3.11
        type=raw,value=r-4.3

  base-r-notebook:
    needs: [env]
    uses: ./.github/workflows/build-test-publish.yml
    secrets: inherit
    with:
      image: base-r-notebook
      labels: |
        org.opencontainers.image.title=Base R Notebook
        org.opencontainers.image.description=Jupyter Lab, Python, and R, and that's it.
      build-args: |
        PYTHON_VERSION=${{ needs.env.outputs.python-version }}
        R_VERSION=${{ needs.env.outputs.r-version }}
      tags: ${{ needs.env.outputs.tags }}
      runs-on: ${{ needs.env.outputs.runs-on }}
      free-space: false
      push: false

  essentials-notebook:
    needs: [env, base-r-notebook]
    uses: ./.github/workflows/build-test-publish.yml
    secrets: inherit
    with:
      image: essentials-notebook
      labels: |
        org.opencontainers.image.title=Essentials Notebook
        org.opencontainers.image.description=CourseKata essentials: everything used in the books.
      tags: ${{ needs.env.outputs.tags }}
      runs-on: ${{ needs.env.outputs.runs-on }}
      push: false

  r-notebook:
    needs: [env, essentials-notebook]
    uses: ./.github/workflows/build-test-publish.yml
    secrets: inherit
    with:
      image: r-notebook
      labels: |
        org.opencontainers.image.title=R Notebook
        org.opencontainers.image.description=CourseKata essentials and other R packages for teaching and learning data science.
      tags: ${{ needs.env.outputs.tags }}
      runs-on: ${{ needs.env.outputs.runs-on }}
      push: false

  datascience-notebook:
    needs: [env, r-notebook]
    uses: ./.github/workflows/build-test-publish.yml
    secrets: inherit
    with:
      image: datascience-notebook
      labels: |
        org.opencontainers.image.title=Data Science Notebook
        org.opencontainers.image.description=R and Python packages for teaching and learning data science.
      tags: ${{ needs.env.outputs.tags }}
      runs-on: ${{ needs.env.outputs.runs-on }}
      push: false
